[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterMarkdown = "997ab1e6-3595-5248-9280-8efb232c3433"
DynamicalSystemsBase = "6e36e845-645a-534a-86f2-f5d4aa5a06b4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TimeseriesPrediction = "f218859d-9706-56aa-9ebf-1fa4ed7b8020"
